# Generated by Django 2.0 on 2017-12-23 21:16

from django.db import migrations, models
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloffschedule',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaloffschedulew10',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='OffSchedule',
        ),
        migrations.DeleteModel(
            name='OffScheduleW10',
        ),
        migrations.RemoveField(
            model_name='historicalonschedule',
            name='consent_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalonschedule',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='historicalonschedule',
            name='visit_code',
        ),
        migrations.RemoveField(
            model_name='historicalonschedule',
            name='visit_code_sequence',
        ),
        migrations.RemoveField(
            model_name='historicalonschedule',
            name='visit_schedule_name',
        ),
        migrations.RemoveField(
            model_name='historicalonschedulew10',
            name='consent_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalonschedulew10',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='historicalonschedulew10',
            name='visit_code',
        ),
        migrations.RemoveField(
            model_name='historicalonschedulew10',
            name='visit_code_sequence',
        ),
        migrations.RemoveField(
            model_name='historicalonschedulew10',
            name='visit_schedule_name',
        ),
        migrations.RemoveField(
            model_name='historicalstudyterminationconclusionw10',
            name='offstudy_datetime',
        ),
        migrations.RemoveField(
            model_name='historicalstudyterminationconclusionw10',
            name='offstudy_reason',
        ),
        migrations.RemoveField(
            model_name='historicalstudyterminationconclusionw10',
            name='offstudy_reason_other',
        ),
        migrations.RemoveField(
            model_name='historicalstudyterminationconclusionw10',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='historicalstudyterminationconclusionw10',
            name='visit_schedule_name',
        ),
        migrations.RemoveField(
            model_name='studyterminationconclusionw10',
            name='offstudy_datetime',
        ),
        migrations.RemoveField(
            model_name='studyterminationconclusionw10',
            name='offstudy_reason',
        ),
        migrations.RemoveField(
            model_name='studyterminationconclusionw10',
            name='offstudy_reason_other',
        ),
        migrations.RemoveField(
            model_name='studyterminationconclusionw10',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='studyterminationconclusionw10',
            name='visit_schedule_name',
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='offschedule_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time subject taken off schedule'),
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusionw10',
            name='offschedule_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time subject taken off schedule'),
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='offschedule_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time subject taken off schedule'),
        ),
        migrations.AddField(
            model_name='studyterminationconclusionw10',
            name='offschedule_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time subject taken off schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='onschedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='onschedulew10',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='HistoricalOffSchedule',
        ),
        migrations.DeleteModel(
            name='HistoricalOffScheduleW10',
        ),
        migrations.RemoveField(
            model_name='onschedule',
            name='consent_identifier',
        ),
        migrations.RemoveField(
            model_name='onschedule',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='onschedule',
            name='visit_code',
        ),
        migrations.RemoveField(
            model_name='onschedule',
            name='visit_code_sequence',
        ),
        migrations.RemoveField(
            model_name='onschedule',
            name='visit_schedule_name',
        ),
        migrations.RemoveField(
            model_name='onschedulew10',
            name='consent_identifier',
        ),
        migrations.RemoveField(
            model_name='onschedulew10',
            name='schedule_name',
        ),
        migrations.RemoveField(
            model_name='onschedulew10',
            name='visit_code',
        ),
        migrations.RemoveField(
            model_name='onschedulew10',
            name='visit_code_sequence',
        ),
        migrations.RemoveField(
            model_name='onschedulew10',
            name='visit_schedule_name',
        ),
    ]
