# Generated by Django 2.0 on 2018-01-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudyterminationconclusionw10',
            name='termination_reason',
            field=models.CharField(choices=[('16_weeks_completed_follow_up', 'Patient completed 16 weeks of follow-up'), ('patient_lost_to_follow_up', 'Patient lost to follow-up'), ('dead', 'Reported/known to have died'), ('consent_withdrawn', 'Withdrawal of Subject Consent for participation'), ('care_transferred_to_another_institution', 'Care transferred to another institution'), ('included_in_error', 'Included in error')], help_text='If included in error, be sure to fill in protocol deviation form.', max_length=75, verbose_name='Reason for study termination'),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusionw10',
            name='termination_reason',
            field=models.CharField(choices=[('16_weeks_completed_follow_up', 'Patient completed 16 weeks of follow-up'), ('patient_lost_to_follow_up', 'Patient lost to follow-up'), ('dead', 'Reported/known to have died'), ('consent_withdrawn', 'Withdrawal of Subject Consent for participation'), ('care_transferred_to_another_institution', 'Care transferred to another institution'), ('included_in_error', 'Included in error')], help_text='If included in error, be sure to fill in protocol deviation form.', max_length=75, verbose_name='Reason for study termination'),
        ),
    ]
