# Generated by Django 2.0 on 2017-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0002_auto_20171219_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='schedule_name',
            field=models.CharField(default='schedule', editable=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusion',
            name='visit_schedule_name',
            field=models.CharField(default='visit_schedule', editable=False, help_text='the name of the visit schedule used to find the "schedule"', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusionw10',
            name='schedule_name',
            field=models.CharField(default='schedule', editable=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalstudyterminationconclusionw10',
            name='visit_schedule_name',
            field=models.CharField(default='visit_schedule', editable=False, help_text='the name of the visit schedule used to find the "schedule"', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='schedule_name',
            field=models.CharField(default='schedule', editable=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyterminationconclusion',
            name='visit_schedule_name',
            field=models.CharField(default='visit_schedule', editable=False, help_text='the name of the visit schedule used to find the "schedule"', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyterminationconclusionw10',
            name='schedule_name',
            field=models.CharField(default='schedule', editable=False, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyterminationconclusionw10',
            name='visit_schedule_name',
            field=models.CharField(default='visit_schedule', editable=False, help_text='the name of the visit schedule used to find the "schedule"', max_length=25),
            preserve_default=False,
        ),
    ]
