# Generated by Django 2.0 on 2017-12-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0002_historicalsubjectlocator_subjectlocator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='action_identifier',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='action_identifier',
        ),
    ]
