# Generated by Django 2.0.1 on 2018-01-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0002_auto_20180104_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deathreport',
            options={'verbose_name': 'Death Report'},
        ),
    ]
