# Generated by Django 2.0.1 on 2018-01-07 18:16

from django.db import migrations, models
import edc_base.model_validators.date


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0003_auto_20180105_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocoldeviationviolation',
            options={'verbose_name': 'Protocol Deviation/Violation', 'verbose_name_plural': 'Protocol Deviations/Violations'},
        ),
        migrations.RemoveField(
            model_name='historicalprotocoldeviationviolation',
            name='date_violation_datetime',
        ),
        migrations.RemoveField(
            model_name='historicalprotocoldeviationviolation',
            name='deviation_or_violation',
        ),
        migrations.RemoveField(
            model_name='historicalprotocoldeviationviolation',
            name='participant_safety_impact',
        ),
        migrations.RemoveField(
            model_name='historicalprotocoldeviationviolation',
            name='participant_safety_impact_details',
        ),
        migrations.RemoveField(
            model_name='historicalprotocoldeviationviolation',
            name='protocol_violation_type',
        ),
        migrations.RemoveField(
            model_name='historicalprotocoldeviationviolation',
            name='protocol_violation_type_other',
        ),
        migrations.RemoveField(
            model_name='protocoldeviationviolation',
            name='date_violation_datetime',
        ),
        migrations.RemoveField(
            model_name='protocoldeviationviolation',
            name='deviation_or_violation',
        ),
        migrations.RemoveField(
            model_name='protocoldeviationviolation',
            name='participant_safety_impact',
        ),
        migrations.RemoveField(
            model_name='protocoldeviationviolation',
            name='participant_safety_impact_details',
        ),
        migrations.RemoveField(
            model_name='protocoldeviationviolation',
            name='protocol_violation_type',
        ),
        migrations.RemoveField(
            model_name='protocoldeviationviolation',
            name='protocol_violation_type_other',
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='report_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time report closed.'),
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='report_status',
            field=models.CharField(choices=[('open', 'Open. Some information is still pending.'), ('closed', 'Closed. This report is complete')], default='Open', max_length=25, verbose_name='What is the status of this report?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='report_type',
            field=models.CharField(choices=[('protocol_violation', 'Protocol violation'), ('protocol_deviation', 'Protocol deviation')], default='protocol_violation', max_length=25, verbose_name='Report type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='safety_impact',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=25, verbose_name='Could this occurrence have an impact on safety of the participant?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='safety_impact_details',
            field=models.TextField(blank=True, null=True, verbose_name='If "Yes", provide details'),
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='violation_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date violation occurred'),
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='violation_type',
            field=models.CharField(choices=[('failure_to_obtain_informed_consent', 'Failure to obtain informed consent'), ('enrollment_of_ineligible_patient', 'Enrollment of ineligible patient'), ('screening_procedure not done', 'Screening procedure required by protocol not done'), ('screening_or_on-study_procedure', 'Screening or on-study procedure/lab work required not done'), ('incorrect_research_treatment', 'Incorrect research treatment given to patient'), ('procedure_not_completed', 'On-study procedure required by protocol not completed'), ('visit_non-compliance', 'Visit non-compliance'), ('medication_stopped_early', 'Medication stopped early'), ('medication_noncompliance', 'Medication_noncompliance'), ('national_regulations_not_met', 'Standard WPD, ICH-GCP, local/national regulations not met'), ('OTHER', 'Other'), ('N/A', 'Not applicable')], default='N/A', max_length=75, verbose_name='Type of violation'),
        ),
        migrations.AddField(
            model_name='historicalprotocoldeviationviolation',
            name='violation_type_other',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='If other, please specify'),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='report_closed_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date and time report closed.'),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='report_status',
            field=models.CharField(choices=[('open', 'Open. Some information is still pending.'), ('closed', 'Closed. This report is complete')], default='Open', max_length=25, verbose_name='What is the status of this report?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='report_type',
            field=models.CharField(choices=[('protocol_violation', 'Protocol violation'), ('protocol_deviation', 'Protocol deviation')], default='protocol_violation', max_length=25, verbose_name='Report type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='safety_impact',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Non', max_length=25, verbose_name='Could this occurrence have an impact on safety of the participant?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='safety_impact_details',
            field=models.TextField(blank=True, null=True, verbose_name='If "Yes", provide details'),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='violation_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Date violation occurred'),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='violation_type',
            field=models.CharField(choices=[('failure_to_obtain_informed_consent', 'Failure to obtain informed consent'), ('enrollment_of_ineligible_patient', 'Enrollment of ineligible patient'), ('screening_procedure not done', 'Screening procedure required by protocol not done'), ('screening_or_on-study_procedure', 'Screening or on-study procedure/lab work required not done'), ('incorrect_research_treatment', 'Incorrect research treatment given to patient'), ('procedure_not_completed', 'On-study procedure required by protocol not completed'), ('visit_non-compliance', 'Visit non-compliance'), ('medication_stopped_early', 'Medication stopped early'), ('medication_noncompliance', 'Medication_noncompliance'), ('national_regulations_not_met', 'Standard WPD, ICH-GCP, local/national regulations not met'), ('OTHER', 'Other'), ('N/A', 'Not applicable')], default='N/A', max_length=75, verbose_name='Type of violation'),
        ),
        migrations.AddField(
            model_name='protocoldeviationviolation',
            name='violation_type_other',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='If other, please specify'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='action_required',
            field=models.CharField(choices=[('remain_on_study', 'Participant to remain on trial'), ('to_be_withdrawn', 'Participant to be withdrawn from trial'), ('remain_on_study_modified', 'Patient remains on study but data analysis will be modified')], default='ww', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='corrective_action',
            field=models.TextField(blank=True, null=True, verbose_name='Corrective action taken'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='corrective_action_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Corrective action date and time'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='preventative_action',
            field=models.TextField(blank=True, null=True, verbose_name='Preventative action taken'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='preventative_action_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Preventative action date and time'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='study_outcomes_impact',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, verbose_name='Could this occurrence have an impact on study outcomes?'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='study_outcomes_impact_details',
            field=models.TextField(blank=True, null=True, verbose_name='If "Yes", provide details'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='violation_description',
            field=models.TextField(blank=True, help_text='Describe in full. Explain how the violation happened, what occurred, etc.', null=True, verbose_name='Describe the violation'),
        ),
        migrations.AlterField(
            model_name='historicalprotocoldeviationviolation',
            name='violation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Explain the reason why the violation occurred'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='action_required',
            field=models.CharField(choices=[('remain_on_study', 'Participant to remain on trial'), ('to_be_withdrawn', 'Participant to be withdrawn from trial'), ('remain_on_study_modified', 'Patient remains on study but data analysis will be modified')], default='ww', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='corrective_action',
            field=models.TextField(blank=True, null=True, verbose_name='Corrective action taken'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='corrective_action_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Corrective action date and time'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='preventative_action',
            field=models.TextField(blank=True, null=True, verbose_name='Preventative action taken'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='preventative_action_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[edc_base.model_validators.date.datetime_not_future], verbose_name='Preventative action date and time'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='study_outcomes_impact',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, verbose_name='Could this occurrence have an impact on study outcomes?'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='study_outcomes_impact_details',
            field=models.TextField(blank=True, null=True, verbose_name='If "Yes", provide details'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='violation_description',
            field=models.TextField(blank=True, help_text='Describe in full. Explain how the violation happened, what occurred, etc.', null=True, verbose_name='Describe the violation'),
        ),
        migrations.AlterField(
            model_name='protocoldeviationviolation',
            name='violation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Explain the reason why the violation occurred'),
        ),
    ]
