# Generated by Django 2.0.1 on 2018-01-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_prn', '0004_auto_20180107_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudyterminationconclusion',
            name='first_line_choice',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('EFV', 'EFV'), ('DTG', 'DTG'), ('NVP', 'NVP'), ('OTHER', 'Other')], default='N/A', max_length=5, verbose_name='If first line:'),
        ),
        migrations.AlterField(
            model_name='studyterminationconclusion',
            name='first_line_choice',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('EFV', 'EFV'), ('DTG', 'DTG'), ('NVP', 'NVP'), ('OTHER', 'Other')], default='N/A', max_length=5, verbose_name='If first line:'),
        ),
    ]
